### ISSUE TITLE
TokenFunction implementation improvements suggestion

### ISSUE THREAD

**Issue by tobyberesford** [NeonXP/MathExecutor#10]
I want to be able to add optional parameters in functions.

Can I propose the following changes to TokenFunction execute function?
1. Add an if statement to see if stack is empty so ->getValue doesn't fire an error if an argument is missing.
   
   if (!(empty($stack))) {        //added to allow it to call function with fewer args
       array_push($args, array_pop($stack)->getValue());  
   }
2. Reverse the resulting array so the arguments are back in the right order before calling the function
   
   $args = array_reverse($args); //array_pop and push flips the order of the arguments so reverse back

Thanks for your consideration.

**Comment by phpfui** [comment]
Closing this.  Lots updated since this was open. If it is still an issue, open a new issue, or better yet, a PR to fix it.  Thanks!
