### ISSUE TITLE
Formula parsing issues

### ISSUE THREAD

**Issue by janlebowski** [NeonXP/MathExecutor#11]
HI,

I have problems parsing simple formulas like this:
- **ROUND(ROUND(0.2456,2),2)** - NXP\Exception\IncorrectExpressionException.
  ROUND() is like this:

``` javascript
        $this->calculator->addFunction('ROUND', function ($decimals, $value) {
            return round($value, $decimals);
        }, 2);
```
- **10/(4-2)** rises exception  NXP\Exception\IncorrectExpressionExceptio also. It looks like the space must be present before 2 here!  

Any ideas how to solve this?
Thank you.

**Comment by dakota** [comment]
Any possible solution to this? Perhaps something I could help with?

**Comment by phpfui** [comment]
Please retry this.  I believe the latest updates will fix this issue.
