### ISSUE TITLE
Should't it throw an exception if a operator is missing?

### ISSUE THREAD

**Issue by underdpt** [neonxp/MathExecutor#112]
Hello,

I'm tinkering with this library, and feels great on my tests so I'm using it for my project.

One question arised on my tests: evaluating the expression `3 4`  returns the value `34`, but I think it really should throw an exception as an operator is missing, and simply removing the space and concatenating the numbers seems counter intuitive to me.

Maybe we should check if previous token is an operator, right parenthesis, etc., and check next token to throw an exception if they result in an incorrect formula?

**Comment by phpfui** [comment]
This seems like a bug.  Would you like to submit a PR to fix it?  Make sure to include tests to prove it works.  Also run the phpcsfixer before submitting so that the new code conforms to the project's coding standards.

**Comment by underdpt** [comment]
Hi,

I've been tinkering with the library to understand how it works, and didn't see a clear way to check this on the current workflow. I think it should be on Tokenizer::tokenize().

Do you have any suggestions?

**Comment by phpfui** [comment]
My first thought was the tokenizer was throwing away spaces, but it looks
like it handles spaces and generates a token for them. But the Calculator
class does not seem to deal with space tokens.

So look in Calculator class. You should be able to throw away space tokens
and then detect var to var collisions. Not sure why it would concatenate
things.

I can take a look sometime next week if you can't find something. Alex
rewrote this code a whole back, so not as familiar with it as the old
version.

**Comment by phpfui** [comment]
I had some time today, so I found the problem.  The tokenizer needs to close any open numbers or strings when it encounters a space.  Then you get an invalid express exception when you go to execute it, which makes sense, as it is not valid.

Will have a new release soon.  Thanks for reporting the issue.

**Comment by underdpt** [comment]
Thanks a lot! 

I've reviewed your changes and it's pretty clear once you know the code :-)
