### ISSUE TITLE
Use of bcmath functions?

### ISSUE THREAD

**Issue by tobiashowitz** [neonxp/MathExecutor#114]
Is it possible that you could replace the simple operations add, sub, mul and div by the operations of `bcmath` to avoid floating point number errors?

Example: `0.1 + 0.2 - 0.3` does not return 0 when using the `MathExecutor` but "5.551115123125783E-17". 

I would like to use your lib for financial calculations, e.g. to calculate the extra fee or a bid price to an offered product. And this calculation is based on a configured formula like "({StockExchangePrice} * 1.025 + 2.30) * 0.9".

**Comment by phpfui** [comment]
The library tried to match what PHP does, but obviously floating point in
PHP has issues.

I think it would be possible to have a bcmath option. Should not be too
hard. You should just have to replace the defaultOperators if the option is
set. Take a look in the MathExecutor class.

Will take a stab at it next week, unless you want to submit a PR for it.

**Comment by phpfui** [comment]
Had some time to do this.  Quite easy in the end.  Let me know if you find any issues.

**Comment by tobiashowitz** [comment]
Great! Thank you for the quick reaction and solution.
One hint: In the Readme.md sector for the new BCMath option there is a small typo in the last sentence. I guess you mean: "Use a plus sign in *front* of any stand alone...".
