### ISSUE TITLE
Too many commas in an if-statement doesn't throw an exception

### ISSUE THREAD

**Issue by madman-81** [neonxp/MathExecutor#116]
If an if-statement has only 1 comma, a \NXP\Exception\IncorrectNumberOfFunctionParametersException is thrown, but if it has too many commas, no exception is thrown and the "if" is calculated with the first 3 parameters. 

```
"if( 'A' == 'A', 1)" => \NXP\Exception\IncorrectNumberOfFunctionParametersException ✔️ 
"if( 'A' == 'A', 1, 2)" => 1 ✔️ 
"if( 'A' == 'A', 1, 2, 3)" => 1 ❌ 
```

If you would add this unit test, it fails:
```php
    public function testFunctionIncorrectNumberOfParametersTooMany() : void
    {
        $calculator = new MathExecutor();
        $this->expectException(IncorrectNumberOfFunctionParametersException::class);
        $calculator->addFunction('myfunc', static function($arg1, $arg2) {
            return $arg1 + $arg2;
        });
        $calculator->execute('myfunc(1,2,3)');
    }
```

I would expect the IncorrectNumberOfFunctionParametersException if there are too many arguments. Otherwise it's impossible to validate formulas. 

Tested with version 2.3.0

**Comment by phpfui** [comment]
Fixed by https://github.com/neonxp/MathExecutor/pull/117
