### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by VitruxPT** [neonxp/MathExecutor#122]
Hi,

I was running a simple test to see if I should be concerned with memory usage when using recursive calculations and I came across this weird memory usage.

I'm using V2.3.0 of this package.

Below is my full code for this test so you can try to reproduce:

This is the function called to run the test in the console
```php
public static function testCalc() {

    $formulas = ['1+1', '2+2', '3+3', '4+4', '5+5'];

    $c = new CalculatorHelper2();

    echo "START | MEMORY USAGE: " . GeneralHelper::memoryUsage() . "\n\n";

    for ($i = 1; $i <= 500000; $i++) {
        foreach ($formulas as $formula) {

            $c->calc($formula);

            echo "MEMORY USAGE: " . GeneralHelper::memoryUsage() . "\n\n";

        }
    }

}
```
    
  This is the Helper class I'm using to wrap the MathExecutor
```php
namespace App\Helpers;

use Exception;

use NXP\MathExecutor;

class CalculatorHelper2
{
    private $executor;

    public function __construct() {

        $this->executor = new MathExecutor();
    }

    public function calc($formula) {
        try {

            return $this->executor->execute($formula, false);

        } catch(Exception $e) {

            echo "ERROR in formula...";

        }
    }

}
```

For additional context this is all the GeneralHelper::memoryUsage function is doing

```php
static public function convertSizes($size) {
    $unit=array('b','kb','mb','gb','tb','pb');
    return @round($size/pow(1024,($i=floor(log($size,1024)))),2).' '.$unit[$i];
}

static public function memoryUsage() {
    return self::convertSizes(memory_get_usage(true));
}
```

In this video we can clearly see the memory usage increasing even though nothing is being saved in memory by creating or modifying any variables (for example adding the results from the calculations to an array)

https://user-images.githubusercontent.com/20666039/209993592-d2f2ce7c-38b3-496a-813d-bd44194d7f7e.mp4

Right when the script starts it seems like it's not increase the memory, however, just two seconds later the memory starts increasing pretty fast after every iteration.

Any idea what's happening here?

**Comment by phpfui** [comment]
I don't see a memory leak. I simplified your code down to the basics (this always very important to do, as you want to make sure only very specific code is executed for an example of a problem).

```php
$formulas = ['1+1', '2+2', '3+3', '4+4', '5+5'];

$executor = new \NXP\MathExecutor();

echo "START | Memory Usage: " . memory_get_usage(true) . "\n\n";

for ($i = 1; $i <= 500000; $i++) {
  foreach ($formulas as $formula) {
    $executor->execute($formula, false);
  }
}
echo "END | Memory Usage: " . memory_get_usage(true) . "\n\n";
```

Memory is the same at the start and end of the program.  I tested PHP 8.1.13 and PHP 8.2.0 under Windows.  They both had the same memory footprint:

```
START | Memory Usage: 2097152

END | Memory Usage: 2097152
```

Let me know if you can reproduce this and we can close this issue.

You might want to look elsewhere in your code.  If memory is an issue for you, try calling unset() in key places to see if that helps.

**Comment by VitruxPT** [comment]
Thanks for you quick reply!

I've been able to track down the issue to the [Laravel](https://github.com/laravel/laravel) project we're using.

**Comment by phpfui** [comment]
Thanks.  Makes sense.  Laravel is a pig.
