### ISSUE TITLE
Error in PHP 7.4

### ISSUE THREAD

**Issue by myhope8729** [neonxp/MathExecutor#128]
It is not working in PHP 7.4

Uncaught Error: syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE)
in \nxp\math-executor\src\NXP\Classes\Operator.php on line 20

How to fix them?

**Comment by phpfui** [comment]
You need to upgrade to PHP 8.0. 7.4 is no longer supported.
