### ISSUE TITLE
Logical operator ! is not supported

### ISSUE THREAD

**Issue by LukasWuethrich** [neonxp/MathExecutor#130]
The README says that the logical operator '!' is supported. However, I always get an exception. Only the logical operator '!=' works.

**Comment by phpfui** [comment]
Try pairing ! with (). !($var) and see if that works. I don't see ! as being tested correctly. Looks like an oversight.

I will see what is involved in a fix.

**Comment by phpfui** [comment]
I tested ! with numbers and variables, and it works fine. Can you provide an expression that fails for you?

**Comment by LukasWuethrich** [comment]
Sorry, my mistake. In my project I still use PHP 7.3 and that's why V2.1.11 was installed. I didn't realize that the logical operator ! was added with v2.3.2.

**Comment by phpfui** [comment]
Not a problem. I added some tests since they were missing.
