### ISSUE TITLE
if() truthy and falsy cases are both executed

### ISSUE THREAD

**Issue by shadoWalker89** [neonxp/MathExecutor#137]
Hi,

In my case i have an `$a` and `$b` variables that are always defined.
I also have a `$c` variable that is only defined when $a > $b

Using this expression

`if($a > $b, $c + 1 : 0)`

I get this exception

NXP\Exception\UnknownVariableException: c

When i debugged this code, i found that `$c + 1` is being parsed and evaluated even if the condition is not true.
This is caused because the if() is being used a custom function and the toknizer is treating it like any other token.
What if the `if()` and all it's 3 parameters, should be a single big token that get parsed on it's own, it will check if the condition is true or false and will call the proper logic depending on the condition being true or false

**Comment by phpfui** [comment]
Melek,

I understand what you are trying to do.

I am not sure if there is a way for the parser to do conditional logic at
that point in the code. But I will try to come up with a workaround for you.

**Comment by phpfui** [comment]
I would add this code if you have a sometimes undefined variable:
```php
$executor->setVarNotFoundHandler(
    function ($varName) {
        if ($varName == 'c') {
            return null;
        }
        throw new \NXP\Exception\UnknownVariableException($varName);
    }
);
```
That will solve your problem.

**Comment by shadoWalker89** [comment]
First of all i want to thank you for your answer.

Yeah i already did that before submitting this issue, but the problem is for something like `5 / $c` i will get an `NXP\Exception\DivisionByZeroException`

If there is no solution for the parser, i think maybe the only solution here is to maybe set it to a high number like 9999

**Comment by phpfui** [comment]
You can set the divide by zero behavior as well if you want as well.  See the readme.md
