### ISSUE TITLE
Request: Please add a new version tag?

### ISSUE THREAD

**Issue by dewalddp** [NeonXP/MathExecutor#14]
Hi,

Firstly, thanks for a great library! The last version was tagged 3 years ago. Do you mind tagging a new version?

Kind Regards,
Dewald

**Comment by phpfui** [comment]
Use dev-master for now.  Working on getting a tag into this repo.

**Comment by phpfui** [comment]
v0.5 is the latest tag now.  Closing this.  Should be supporting versions correctly going forward now.
