### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by adlabac** [NeonXP/MathExecutor#29]
If an expression begins or ends with an operator, instead of throwing an Exception the **Fatal error** occurs (the only working scenario is when the expression begins with the minus sign).

For example:

`echo $calculator->execute('*1+2');` or `echo $calculator->execute('1+2-');`.

Also, in case when the expression begins with the plus sign it should be evaluated:

`echo $calculator->execute('+1+2');`

The error message:

> Fatal error: Uncaught Error: Call to a member function getValue() on null in ...\vendor\nxp\math-executor\src\NXP\Classes\Token\TokenPlus.php on line 50
>
>Error: Call to a member function getValue() on null in ...\vendor\nxp\math-executor\src\NXP\Classes\Token\TokenPlus.php on line 50

**Comment by phpfui** [comment]
I will have a fix for this shortly.  It will solve the 1+2- issue (or 1+2+-* type things).  It will not the +1+2 issue as I don't think that is really a valid expression.  -1+2 does work as -1 is a valid value. For +2, the plus is not really needed.  If you still have an issue after the upcoming fix, please submit a PR and we can look at it.

**Comment by adlabac** [comment]
Why do you think "+2" is not a valid espression. In this case "+" is the **sign** of the number which indicates a positive number, and it's perfectly valid. I don't know of any language/application/calculator which to not accept this.

Wikipedia says:

> The positivity of a number may be emphasized by placing a **plus sign before** it, e.g. +3. In general, the negativity or positivity of a number is referred to as its **sign**.

**Comment by phpfui** [comment]
Positive numbers are generally not signed. But I will look into adding this.

Got into my old email account, but switched git hub over to my Gmail.  Should have an update shortly.

Will try to find the invite as well.

On Thursday, October 25, 2018 Aleksandar Dlabač <reply@reply.github.com> wrote:



Why do you think "+2" is not a valid expression? In this case "+" is the sign of the number which indicates a positive number, and it's perfectly valid. I don't know of any language/application/calculator which to not accept this.

Wikipedia says:

The positivity of a number may be emphasized by placing a plus sign before it, e.g. +3. In general, the negativity or positivity of a number is referred to as its sign.

**Comment by phpfui** [comment]
This is fixed in the latest version.
