### ISSUE TITLE
Quoted arguments

### ISSUE THREAD

**Issue by NeonXP** [NeonXP/MathExecutor#40]
In readme:

> Expressions can contain double or single quoted strings that are evaluated

In fact:
```$result = $executor->execute('DATE("2019-01-09 04:08:00")');``` - works (argument = "2019-01-09 04:08:00")
```$result = $executor->execute("DATE('2019-01-09 04:08:00')");``` - error (argument = "00")

Need to investigate.

**Comment by phpfui** [comment]
Yeah, that should work.  Or maybe we change the docs to just say " only.  If I have time tomorrow at the office I will look into it and do a fix.  Should be easy.

**Comment by NeonXP** [comment]
As I can see this PR fixes problem: https://github.com/NeonXP/MathExecutor/pull/41
Most interesting parts: 
https://github.com/NeonXP/MathExecutor/pull/41/files#diff-6cc22a7baf05dfdfd398f40e723eda84 and https://github.com/NeonXP/MathExecutor/pull/41/files#diff-4923723f9fcc2322d82bd9d29ba6b1eaR149

**Comment by NeonXP** [comment]
Fixed by https://github.com/NeonXP/MathExecutor/pull/41
