### ISSUE TITLE
Subtractions in expressions results in error

### ISSUE THREAD

**Issue by fr0z3nfyr** [neonxp/MathExecutor#45]
Consider the same expression written slightly differently below:

1. `(1+2+3+4-5)*7/100`
2. `( 1 + 2 + 3 + 4 - 5 ) * 7 / 100`

The first one fails while the second one works perfectly well. It seems, in the tokens are not created correctly if there is no space between `-` operator. Seems somewhat related to #1 

Error at `nxp\math-executor\src\NXP\MathExecutor.php line 235`

**Comment by phpfui** [comment]
Thanks for the bug report.  Now fixed in  v0.8.0
