### ISSUE TITLE
Token Greater Than Or Equals

### ISSUE THREAD

**Issue by begicf** [neonxp/MathExecutor#47]
Hi, 

I wont to write the token '>=', it always the separate the rule in two strings '>' and '=' . 

I wrote the class but regex doesn't resolve the rules very well.
Do you have any suggestion ? 

`  /**
     * @return string
     */
    public static function getRegex() {
        return '\>\=';
    }`

**Comment by phpfui** [comment]
Glad this seems to work for you.  Going to close for now.  Open a new issue if you have more questions.

And thanks for using MathExecutor!
