### ISSUE TITLE
Removal of symbolic links

### ISSUE THREAD

**Issue by franksl** [neonxp/MathExecutor#52]
Hi,
I'm deploying these library in a complex environment that uses automated scripts.
I get errors with the bin/phpunit symbolic link because it's not always installed. Also I think that, in general it should not be in this package because it's an external dependency that should be resolved in another way.
If you agree please remove the link,
Thanks,
Franco

**Comment by phpfui** [comment]
I am actually not sure why it is there, or even what it is.  I am a Windows guy and helping Alex maintain this project.  Alex probably knows more.  But I agree with you it probably should not be there.

Can you submit a PR? I would be happy to merge it in and do a release.  Can do so as soon as you submit.

Thanks.

**Comment by phpfui** [comment]
I can probably do this myself tomorrow night, but happy to merge a PR whenever.

**Comment by franksl** [comment]
Hi,
Here's the [pull request](https://github.com/neonxp/MathExecutor/pull/53)

**Comment by phpfui** [comment]
Thanks for the PR!  Go grab V1.1.1
