### ISSUE TITLE
`If` condition breaks since v2.x

### ISSUE THREAD

**Issue by Bosbaba** [neonxp/MathExecutor#66]
Hi Alexander, thx for the create project. Don't know if this is a bug, or a code change require(Couldn't find any release notes regarding this change). 

If we upgrade from 1.1.4 to 2.0.x the `if` condition doesn't seem to work any more.

Expression used `if($trx_amount < 40000, $trx_amount * 0.06, if($trx_amount < 60000, $trx_amount * 0.05, $trx_amount * 0.03))`

```
NXP\Exception\UnknownOperatorException:  in file /var/www/vendor/nxp/math-executor/src/NXP/Classes/Tokenizer.php on line 253
Stack trace:
  1. NXP\Exception\UnknownOperatorException-&gt;() /var/www/vendor/nxp/math-executor/src/NXP/Classes/Tokenizer.php:253
  2. NXP\Classes\Tokenizer-&gt;buildReversePolishNotation() /var/www/vendor/nxp/math-executor/src/NXP/MathExecutor.php:349
  3. NXP\MathExecutor-&gt;execute()
```

**Comment by phpfui** [comment]
Thanks for the heads up. Alex or I should be able to get this resolved
today.

**Comment by phpfui** [comment]
I added https://github.com/neonxp/MathExecutor/pull/67 to fix this.  Alex should be merging it soon.

Root problem was with variables actually and not functions, so a good find!

Thanks.

**Comment by Bosbaba** [comment]
Thx for the quick turn around time guys 👍

**Comment by phpfui** [comment]
My pleasure. Thanks for the heads up.

This is how you make great software.
