### ISSUE TITLE
Allow optional parameters in functions

### ISSUE THREAD

**Issue by javiermarinros** [neonxp/MathExecutor#71]
It would be a great feature allow functions to have optional parameters.

For example:

```
 'log' => function ($arg, $base = null) {
                return isset($base) ? log($arg, $base) : log($arg);
            },
```

Or

```
   'if' => function ($expr, $trueval, $falseval = 0) {
                if ($expr === true || $expr === false) {
                    $exres = $expr;
                } else {
                    $exres = $this->execute($expr);
                }
                if ($exres) {
                    return $this->execute($trueval);
                } else {
                    return $this->execute($falseval);
                }
            }
```

I tried to implement it using [`ReflectionFunction`::`getNumberOfRequiredParameters`](https://www.php.net/manual/es/reflectionfunctionabstract.getnumberofrequiredparameters.php) but the parser stack gets in bad state and the execution fails.

This change could even open the door to have an arbitrary number of parameters for some functions, eg.: `max(1, 2, 3, 4, 5)`

**Comment by phpfui** [comment]
I agree, but I looked into it with the previous parser and decided it could
not work.

But if you figure out a way to make it work, I am all for it.
