### ISSUE TITLE
Create aliases ln (for log), lg (for log10)

### ISSUE THREAD

**Issue by diman3210** [neonxp/MathExecutor#75]
Users often write lg and ln to calculate the natural and decimal logarithms.

**Comment by phpfui** [comment]
Good idea.  Do you want to submit a PR?

Bruce

**Comment by diman3210** [comment]
yes

**Comment by diman3210** [comment]
how do I do this?

**Comment by phpfui** [comment]
Fork the project in GitHub, pull it down locally, create a branch off of
master called functions or something like that.  Do you work in that
branch.  Run unit tests, add some unit tests.  When you think it is all
working, push branch.  Go back to GitHub and open a Pull Request on our
project, referencing yours.  GitHub fixed this up recently, so should be
straightforward.

Let me know if you have any questions or problems you can't figure out.
Contributing to open source is fun!

Bruce

**Comment by phpfui** [comment]
Now in V2.1.5.

Thanks for the PR.
