### ISSUE TITLE
$lexer->stringToTokensStream($expression) not working anymore

### ISSUE THREAD

**Issue by zzal** [NeonXP/MathExecutor#8]
Hi,

I'm having trouble executing some simple formulas since last update. I'm having this simple formula: `'line1 + line2 + line3 + line4'`

I checked and my variables in my MathExecutor instance and they are well defined:

```
array (size=8)
  'pi' => float 3.14159265359
  'e' => float 2.71828182846
  'line1' => float 162766
  'line2' => float 31417
  'line3' => float 1319
  'line4' => float 1131
  'line5' => float 166809
  'line6' => float 36372
```

I found that it's when it passing trough `$tokenFactory->createToken($token);` (Lexer class, line 50) that it throws me an `UnknownFunctionException`. The `$token` at that time is equal to `'line1'`, so I guess that it's trying to find my variable inside its operators list, but I may be wrong.
I'm asking myself, is it OK however that there's an empty function (`public function addVariable`) in the TokenFactory class? 

Must point out that my code was woorking perfectly before Sep 05 changes.

I tried it with PHP 5.3 and 5.5 with same errors.
Thanks!

**Comment by phpfui** [comment]
Suggested solution is correct.  Variables need to start with $.  Functions do not.  Closing.
