### ISSUE TITLE
Prevent cache while executing an expression

### ISSUE THREAD

**Issue by msztorc** [neonxp/MathExecutor#80]
Hi,

It would be great to have optional boolean type param `$cache = true` for `execute` method to prevent storing tokens in the cache. 

```
public function execute(string $expression, bool $cache = true)
```

I'm aware of all benefits of having a cache. However, this can be undesirable in some cases, especially if you want to use a particular expression just only once or you if need to parse thousands of unique expressions at the same class instance. This will impact memory usage a lot because of adding thousands of expression tokens to `$cache` variable and they will never be used again.

According to the above, I suggest adding optional param `$cache = true` to `execute` method and additional public method to clear cache if needed.

**Comment by phpfui** [comment]
Sounds reasonable.  Really the cache should be a WeakMap as well, but that is PHP 8 only.

Do you want to submit a PR for this?

**Comment by msztorc** [comment]
sure, I will do that.

**Comment by msztorc** [comment]
PR #81

**Comment by phpfui** [comment]
Now in V2.1.6

**Comment by phpfui** [comment]
Latest now live on http://phpfui.com/?n=NXP&c=MathExecutor
