### ISSUE TITLE
Object Variables

### ISSUE THREAD

**Issue by mrm** [neonxp/MathExecutor#97]
Hi, I'm using MathExecutor in combination with a money library to calculate prices (without floating point errors).

I've extended MathExecutor and overwritten all the operators to also work with with Money objects and it works great, however setting variables is not possible as it only allows for scalar types. Unfortunately I can't override the `setVar` function as `$variables` is private.

A simple fix would be to put the validation in a separate function so it's possible to override it, or make the `$variables` array protected. Not sure if this might cause problems in other areas though. 

I'd be happy to create a PR for the above or for a different solution if you're willing to accept it.

**Comment by phpfui** [comment]
$variables should probably not be private.  But open for a PR. I think we added the scalar test to try to make it more type safe. But what we really want is an object we can perform math on.  I don't know of a way to specify that in PHP, as PHP does not yet support operator overloading, which is really what we need.

Making properties protected might just be enough.

But I like an overridable validation function.  Then you can easily add valid types and still get some type protection.

Maybe do both?

**Comment by phpfui** [comment]
Another possibility would be a validation callback.  It would default to what it does now, but you could pass a callback. That way you would not have to override a function.

**Comment by phpfui** [comment]
Issue resolved with next release, closing.
